base:
  # data_dir: "/mnt/traffic/maruokai/datasets/pd_data"
  data_dir: "/mnt/DataCenter/maruokai/datasets/pd"
  csv_dir: "/home/maruokai/workplace/pd/medication_detection/user_data_split"
  base_model_path: "/home/maruokai/workplace/pd/subject_detection/runs/2022-06-24_21:14:44/best_ckpt.pth"
  check:
    Immediately before Parkinson medication: True
    I don't take Parkinson medications: False
    Another time: False
    Just after Parkinson medication (at your best): True
train:
  lr: 1e-2
  batch_size: 64
  epoch: 200
  gpu: 0
  rate: 0.8